The beneficiary’s recognized expertise in systems engineering and MBSE has led to pivotal roles evaluating and shaping the work of peers in prestigious academic and professional forums.

    Technical Chair for CSER 2020 (Conference on Systems Engineering Research):
    As Technical Chair, the beneficiary managed the peer review process for over 70 submitted research papers, selecting and coordinating expert reviewers, ensuring the integrity and quality of the technical program, and ultimately influencing the state of knowledge disseminated at one of the leading conferences in the systems engineering domain. This role required discerning technical judgment, the ability to evaluate cutting-edge research against established criteria, and strong leadership to guide the scientific community toward advancements in MBSE, digital twin integration, and related areas.

    Peer Reviewer for IEEE Systems Journal and Other Scholarly Publications:
    The beneficiary served as a peer reviewer for manuscripts submitted to the IEEE Systems Journal—one of the top-tier venues for systems-related research—and other reputable publications. Acknowledged by editorial teams for providing insightful, thorough, and constructive reviews, the beneficiary’s evaluative work ensured that only high-quality, rigorously validated research reached publication. This process involved assessing methodological soundness, verifying the significance of contributions, and suggesting improvements that refine the field’s overall standards.

These evaluative roles—as Technical Chair and peer reviewer—demonstrate that the beneficiary’s expertise is trusted by leading academic and professional entities. By guiding the selection and improvement of published research, the beneficiary has played a direct role in shaping the discourse, direction, and quality of scholarly work in MBSE and complex systems engineering. This capacity to critically appraise and elevate others’ contributions is a hallmark of recognized leaders and innovators in the field.
