Name: Shatad Kolin Purohit

Field of Endeavor: Systems Engineering, Digital Twin Technology, AI-Driven Model-Based Systems Engineering (MBSE), and Complex Systems Architecting.
Proposed Job Title & Employer in the U.S.: Senior Systems Engineer / Systems Architect at RTX Corporation
Proposed U.S. Work Description:
The beneficiary will lead cutting-edge research and development initiatives focused on integrating digital twin technology with advanced MBSE (Model-Based Systems Engineering) methodologies to improve complex aerospace, automotive, and manufacturing systems. In this capacity, the beneficiary will develop and refine ontology-driven frameworks and AI-enhanced knowledge representation techniques to ensure seamless interoperability between hardware and software components. They will deploy model-based systems engineering, digital threads, digital twins across product lifecycles, guide the strategic adoption of MBSE for major industry clients, optimize systems architecture, and accelerate the design and analysis of next-generation engineered systems. By leveraging their pioneering work in digital twins and generative AI models, the beneficiary will deliver transformative solutions that significantly enhance system reliability, reduce development costs, and speed time-to-market in critical technology sectors.

Field of Endeavor and Key Concepts
The beneficiary’s field of endeavor—encompassing Systems Engineering, Digital Twin Technology, AI-Driven Model-Based Systems Engineering (MBSE), and Complex Systems Architecting—lies at the intersection of advanced engineering methodologies and cutting-edge computational tools. This domain addresses the increasing complexity, scale, and interconnectedness of modern aerospace, automotive, manufacturing, and defense systems.
•	Model-Based Systems Engineering (MBSE):
MBSE is a methodology that uses high-fidelity models as the central artifact for the conceptualization, design, analysis, verification, and validation of complex systems. Instead of relying on traditional, document-centric approaches, MBSE employs interconnected models to capture system requirements, structure, behavior, and constraints. This approach ensures greater consistency, traceability, and reusability of system knowledge, enabling engineers to manage complexity more effectively and make informed decisions across the entire system lifecycle.
•	Digital Twin Technology:
A digital twin is a highly accurate, virtual representation of a physical asset, system, or process. It incorporates real-time data and historical information, allowing engineers and decision-makers to monitor, simulate, predict, and optimize performance under varying conditions. For example, a digital twin of an aircraft might integrate sensor data from flight operations, maintenance records, and simulation models, enabling stakeholders to test design upgrades, predict failures, reduce operational costs, and enhance safety without disrupting real-world operations.
•	Digital Thread:
The digital thread is a communication framework that links all the information generated throughout the lifecycle of a product (from initial design through manufacturing, deployment, operation, and maintenance) into a single, accessible environment. By ensuring that each stakeholder in the value chain—such as engineers, suppliers, and maintenance crews—has access to the right information at the right time, the digital thread improves collaboration, reduces the risk of errors, and accelerates time-to-market.
•	AI-Driven Approaches (e.g., Generative Models, Ontologies):
To handle the increasing complexity of modern engineering systems, the beneficiary employs advanced Artificial Intelligence (AI) techniques, including transformer-based generative models. These AI tools help automate aspects of the modeling process—such as generating digital twin architectures, exploring design tradespaces, or identifying patterns in large datasets. Ontologies and formal knowledge representation methods further ensure that complex relationships between system components are well-defined, enabling automated reasoning, intelligent queries, and improved decision-making.

Academic and Professional Qualifications:
The beneficiary holds a Ph.D. in Astronautical Engineering with a specialization in Systems Architecting and Engineering from the University of Southern California (USC)—a globally top-ranked research institution renowned for its aerospace and systems engineering programs. Prior to this, the beneficiary earned an M.S. in Systems Architecting and Engineering from USC, further establishing a deep foundational knowledge and skill set in complex systems design, analysis, and lifecycle management.
These graduate-level degrees provided the beneficiary with advanced theoretical and applied insights into MBSE, digital twin methodologies, and AI-driven decision support frameworks, all of which are directly relevant to the beneficiary’s field of endeavor.
To enhance professional acumen, the beneficiary also completed a Professional Certificate in Architecture and Systems Engineering from the Massachusetts Institute of Technology (MIT)—a program developed in partnership with NASA and Boeing. This certificate underscores the beneficiary’s capability to manage complexity and apply rigorous engineering principles at scale. Furthermore, earning the OMG Certified Systems Modeling Professional (OCSMP) Model Builder–Intermediate certification demonstrates the beneficiary’s mastery of the Systems Modeling Language (SysML) and related MBSE tools, crucial for developing robust, model-centric engineering practices.
Collectively, the beneficiary’s doctoral and master’s degrees from USC, alongside specialized MIT training and formal SysML certification, position the beneficiary as a leading expert. These credentials establish both the technical depth and breadth necessary to guide transformative research and development initiatives that integrate digital twins, MBSE, and advanced AI techniques into complex aerospace, automotive, and manufacturing systems.


(1)	Prizes or Award for Excellence
Jenny Wang Excellence in Teaching Award (USC Viterbi School of Engineering, May 2024):
This prestigious award is conferred upon exceptional teaching assistants and instructors who have made significant contributions to course quality, student engagement, and curriculum innovation within the USC Viterbi School of Engineering. The beneficiary received this award for designing and delivering innovative educational materials in Model-Based Systems Engineering (MBSE), including content developed through a National Science Foundation (NSF) PEER-funded project focused on advanced manufacturing and digital twin technology.
As part of the NSF PEER project, the beneficiary created and integrated cutting-edge course modules—such as “Digital Twin-Enabled MBSE for Manufacturing”—into graduate-level engineering curricula. These modules introduced state-of-the-art concepts, practical case studies, and hands-on activities that enhanced the learning experience and directly supported NSF’s objective of advancing engineering education and workforce readiness. The beneficiary’s teaching approach emphasized interactive learning, ontology-based MBSE techniques, and matrix-based methods for analyzing complex systems—practices that garnered commendations from both students and faculty. In essence, the Jenny Wang Excellence in Teaching Award recognizes the quality, impact, and innovation of these teaching methods, which were significantly influenced and improved by the NSF-backed educational advancements and course materials.
________________________________________
Best Research Assistant Award (USC Viterbi School of Engineering, May 2024 and May 2022):
The beneficiary earned this award in recognition of exemplary performance, leadership, and sustained research contributions as a Graduate Research Assistant over multiple years at USC. During this period, the beneficiary developed methodologies to integrate digital twin technology and generative models within MBSE frameworks. These efforts supported research funded by the NSF, General Motors (GM), and the Department of Defense’s Systems Engineering Research Center (SERC), and contributed to advancing next-generation aerospace systems and complex manufacturing solutions.
In these roles, the beneficiary formulated advanced ontologies, applied formal logic and mathematical reasoning to represent system knowledge consistently, and implemented transformer-based generative AI models to accelerate the creation and analysis of digital twins. This approach enabled more efficient simulation of complex aircraft systems and informed critical design decisions. Throughout this tenure, the beneficiary collaborated closely with faculty, industry partners, and interdisciplinary teams, ensuring that resulting frameworks were both technically robust and practically valuable. The Best Research Assistant Award acknowledges these technical innovations, the ability to drive projects forward, adherence to rigorous academic standards, and the creation of industry-relevant solutions that bridge theoretical research with applied engineering practice.
________________________________________
Orange County Engineering Council: Outstanding Engineering Student Award (2020):
This honor recognized the beneficiary’s exceptional academic achievements, research productivity, and leadership in engineering endeavors. Key factors included groundbreaking work in MBSE, contributions to NSF PEER project activities that integrated MBSE principles into advanced manufacturing curricula, research on the economic justification for MBSE adoption, and the development of digital twin-enabled frameworks. Active involvement in industrial collaborations (e.g., with GM) further demonstrated the beneficiary’s capability to enhance industry readiness and workforce development. This award signifies the beneficiary’s status as an emerging leader in engineering innovation, successfully bridging theory, practice, and education to support diverse industry sectors.
________________________________________
2020 Engineers’ Council Distinguished Engineering Project Achievement Award:
This award honored the beneficiary’s involvement in a pioneering research project focused on adaptive cyber-physical-human systems. The recognized achievements included the development of a context-sensitive dashboard for monitoring and controlling UAV swarms and self-driving vehicles—work closely aligned with system-of-systems modeling and digital twin experimentation testbeds. Leveraging MBSE principles, formal methods refined during NSF-related projects, and integrated autonomy-human teaming frameworks, the beneficiary contributed to innovative solutions that push the frontiers of complex system architecting and digital engineering strategies.
________________________________________
Second Place in RaceOn Self-Driving Robot Competition at USC (2019):
Earning second place in this competition highlighted the beneficiary’s hands-on expertise in autonomous systems engineering—a domain where digital twin principles and MBSE-informed architectures can substantially improve reliability and performance. Drawing on insights from MBSE methods, NSF-influenced research testbed experiences, and advanced system modeling techniques, the beneficiary integrated sensor fusion, control logic, and robust architectural designs into a small-scale autonomous robot. This recognition attests to the beneficiary’s technical acumen, teamwork, and ability to apply systems engineering concepts to real-world, time-sensitive challenges.
________________________________________
Multiple Entrepreneurial Recognition Awards (Blackstone Innovation Challenge, Wrigley Sustainability Prize finals, Min Family Challenge, Maseeh Entrepreneurship Prize Competition):
These entrepreneurial awards highlight the beneficiary’s capacity to translate core systems engineering concepts—particularly those grounded in MBSE and digital twin frameworks—into market-responsive solutions that address socio-technical and sustainability challenges. Leveraging insights from NSF curriculum development (e.g., digital twin-enabled manufacturing) and a broad research portfolio, the beneficiary proposed innovative concepts aimed at optimizing complex supply chains, resource utilization, and sustainable operations. These recognitions reflect the beneficiary’s aptitude for identifying industry and societal needs, formulating data-driven, model-based solutions, and effectively conveying their value to investors, judges, and end-users.



------------------------------------------------------------------
(2) Membership in Associations Requiring Outstanding Achievements
While the beneficiary’s memberships may not be exclusively in associations that strictly require extraordinary achievements for admission, the beneficiary’s active and recognized leadership roles within highly respected professional organizations reinforce the beneficiary’s standing in the field.
•	International Council on Systems Engineering (INCOSE):
The beneficiary has made significant, recognized contributions to INCOSE initiatives, demonstrating more than passive membership. Specifically, the beneficiary contributed to the development and implementation of a Systems Engineering Lab (SE Lab) aimed at providing INCOSE members with state-of-the-art tools for learning, research, and professional development. By helping to define the SE Lab’s architecture, selecting appropriate tools, and guiding integration strategies, the beneficiary ensured that INCOSE members—who are often established systems engineers from industry, academia, and government—had access to advanced capabilities that enhance their understanding and application of MBSE and digital twin concepts. These efforts also encouraged collaboration among experts, fostering a vibrant community of practice within INCOSE.
•	IEEE Systems, Man, and Cybernetics (SMC) Society:
In addition to INCOSE contributions, the beneficiary served as Outreach Manager for initiatives bridging IEEE SMC and INCOSE, forging new alliances between two major professional communities. By facilitating workshops, panel discussions, and joint working groups, the beneficiary played a crucial role in promoting knowledge exchange, advancing MBSE techniques, and identifying emerging trends in digital engineering. This proactive engagement in professional societies—recognized for their selective and expert-driven communities—demonstrates a leadership role that goes beyond standard membership. Such contributions indicate peer acknowledgment of the beneficiary’s expertise, organizational acumen, and ability to influence the direction of systems engineering research and practice on an international scale.


---------------------------------------------------------------------------------------------------
(3) Published Material About the Beneficiary in Professional or Major Trade Publications
•	Feature on Siemens Software Network (Siemens Blog):
The beneficiary’s work was highlighted in a blog post published by the Siemens Software Network—an authoritative platform widely read by engineering professionals worldwide. In the article titled “Engineering for Change with USC Ph.D. Student, Shatad Purohit” (April 29, 2021), Siemens spotlighted the beneficiary’s pioneering research at the University of Southern California, focusing on digital twins, MBSE methodologies, and sustainable system design. Siemens, a global leader in engineering software and industrial automation, rarely profiles individual researchers at length. That they chose to feature the beneficiary’s insights underscores the beneficiary’s relevance, thought leadership, and influence in guiding engineering education and the next generation of systems engineering tools. The publication emphasized the beneficiary’s holistic approach—integrating economics, ecology, and policy—further demonstrating the beneficiary’s recognized standing in the international engineering community.









--------------------------------------------
(5) Original Scientific, Scholarly, or Business-Related Contributions of Major Significance
The beneficiary’s research and innovations have significantly advanced the state of systems engineering, digital twin technology, and Model-Based Systems Engineering (MBSE). These original contributions have been acknowledged by leading academic institutions, major government research agencies, and prominent industry stakeholders. Their influence is reflected in strong citation metrics, direct industrial adoption, and integration into strategic decision-making processes across multiple sectors.
1.	Integration of Digital Twins with MBSE:
The beneficiary pioneered a methodology seamlessly integrating digital twin technology into MBSE frameworks, enabling unified, lifecycle-spanning representations of complex aerospace and automotive systems. Peer-reviewed publications on this topic have been presented at premier conferences (e.g., IEEE SMC, AIAA SciTech) and subsequently implemented by industry leaders, notably General Motors. This technology transfer underscores the practical importance of these methods in guiding large-scale engineering programs and optimizing system development pipelines.
2.	Ontology-Driven Knowledge Representation and Reasoning:
The beneficiary introduced advanced, ontology-based modeling techniques that employ formal logic and mathematical reasoning to systematically capture and manage intricate system architectures. This approach enhances data consistency, interoperability, and traceability. As a result, engineering teams can more efficiently navigate complex design decisions, reduce costly integration issues, and streamline their progression from concept to implementation. Such improvements are supported by citations and endorsements from organizations like NASA’s Jet Propulsion Laboratory (JPL), the German Aerospace Center (DLR), and top academic institutions (e.g., MIT, Caltech, Stevens Institute of Technology).
3.	AI-Enabled Generative Modeling for System Upgrades and Rapid Iteration:
Incorporating transformer-based generative AI models into the digital twin ecosystem represents a groundbreaking contribution to the field. By automating model creation, refinement, and scenario analysis, this innovation empowers engineers to rapidly evaluate multiple design options and emerging technologies with minimal manual intervention. This capability enables key industry players—such as aerospace and defense contractors—to respond swiftly to market demands and maintain a competitive edge in high-stakes, safety-critical domains.
4.	Economic Analysis and Justification of MBSE Adoption:
The beneficiary’s economic analysis framework for MBSE adoption has proven to be one of the most impactful contributions in the field. One seminal journal publication has amassed over 135 citations—an exceptionally high figure for the systems engineering domain—reflecting its widespread acceptance and utility. This work has been referenced by NASA, JPL, DLR, Dassault Systèmes, and numerous academic institutions across the globe. Dassault Systèmes, a leading provider of engineering software, has even leveraged insights from this analysis in its product strategy definition. By quantifying cost-benefit factors and life cycle advantages, this contribution provides decision-makers with actionable intelligence for strategic planning and risk mitigation, influencing both industry best practices and policy-level discussions.
5.	Development of a Digital Twin-Enabled MBSE Testbed and Curriculum:
The beneficiary established a digital twin-enabled MBSE research testbed that serves as a proving ground for novel modeling constructs, verification methods, and system-of-systems integration strategies. Supported by National Science Foundation (NSF) grants and industry collaborations, this testbed, along with the beneficiary’s educational modules, has accelerated the dissemination of best practices. These curriculum enhancements have enriched engineering education and prepared a more capable workforce to meet the demands of advanced manufacturing and complex system architecting—outcomes recognized by students, faculty, industry partners, and accrediting bodies.
Recognition and Impact:
Collectively, these original contributions have led to:
•	High citation counts (over 196 citations in total, with the primary economic analysis paper cited 135 times) in academic literature, reflecting their foundational importance in the field.
•	Adoption and reference by industry leaders (e.g., GM, Dassault Systèmes), confirming their practical relevance and usability in shaping product strategies and engineering roadmaps.
•	Acknowledgment by leading research institutions and governmental organizations (NASA, JPL, DLR), underlining their credibility, rigor, and significance to ongoing research agendas.
These achievements represent sustained, transformative advancements in how complex systems are conceived, designed, validated, and sustained, cementing the beneficiary’s position as a pioneering figure in systems engineering and digital twin-enabled MBSE.

Challenges Addressed and Significance of the Beneficiary’s Work
The aerospace, automotive, and manufacturing sectors face numerous challenges as systems grow more intricate and interconnected. Traditional approaches often struggle to maintain consistency, traceability, and rapid adaptation when dealing with complex requirements, evolving technologies, and geopolitical and environmental constraints.
The beneficiary’s research overcomes these hurdles by:
1.	Enhancing Decision Quality:
By integrating MBSE with digital twins and AI-driven reasoning, the beneficiary’s methodologies enable stakeholders to evaluate alternative system architectures, predict the outcomes of design changes, and manage complexity more effectively. This leads to more reliable products, reduced lifecycle costs, and shorter development cycles.
2.	Promoting Interoperability and Lifecycle Coverage:
The beneficiary’s contributions to ontology-driven frameworks and digital thread integration ensure that data and knowledge flow seamlessly among different tools, teams, and life cycle phases. This interoperability helps organizations avoid costly rework and enables holistic optimization of complex systems, ultimately benefitting national industries, consumers, and workforce competitiveness.
3.	Influencing Industry Strategies and Best Practices:
With publications cited by NASA, JPL, DLR, and leading firms like Dassault Systèmes, and through collaborations with major industry players (e.g., General Motors, Raytheon Technologies), the beneficiary’s work has directly informed product strategies, enhanced tool capabilities, and guided policy-level decision-making. This thought leadership strengthens the country’s competitive edge in high-stakes sectors such as defense, aerospace, and advanced manufacturing.
4.	Advancing Workforce Development and Education:
By integrating cutting-edge research findings into curricula funded by the National Science Foundation (NSF) and establishing communities of practice (e.g., SAE Digital Twin Community, INCOSE SE Lab initiatives), the beneficiary’s work helps develop a more skilled and future-ready engineering workforce. This educational impact ensures that students and practicing engineers alike can leverage the latest MBSE and digital twin technologies, bolstering the innovation capacity of the U.S. engineering ecosystem.
Impact on the Field and Nation
The beneficiary’s contributions address national priorities such as maintaining technological leadership in aerospace and defense, ensuring the resilience and efficiency of critical infrastructure systems, and fostering sustainable solutions that balance economic, ecological, and social considerations. By enabling more agile engineering practices, the beneficiary’s methods help U.S. industries respond swiftly to changing market demands, regulatory pressures, and environmental challenges.
This work not only provides organizations with the tools to innovate rapidly and reliably but also sets new standards for how complex engineering problems are approached. In doing so, the beneficiary’s research contributes to safer, more efficient transportation, cleaner energy production, resilient supply chains, and improved national security—all of which are vital to the country’s economic and strategic interests.


-----------------------------------------------------------------------------------------------
(6) Authorship of Scholarly Articles in the Field
The beneficiary’s authorship record demonstrates sustained scholarly influence in the fields of Model-Based Systems Engineering (MBSE), digital twin technology, and complex systems architecting. Numerous peer-reviewed publications in high-impact journals, leading conferences, and authoritative reference works reflect the beneficiary’s thought leadership and the broad recognition of these contributions by academic, government, and industry stakeholders.
•	Peer-Reviewed Journal Articles in High-Impact Venues:
The beneficiary has published in the IEEE Systems Journal (JCR Q1, Impact Factor 5.28) and MDPI Systems Journal, both of which are considered prestigious and selective outlets for cutting-edge research in systems engineering. These publications are frequently cited by scholars, research laboratories (NASA, JPL, DLR), and industry practitioners (e.g., Dassault Systèmes), underscoring their influence and practical relevance.
•	Conference Papers at Premier Venues:
The beneficiary has presented research findings at leading conferences such as IEEE SMC (with an Impact Score of ~3.3), AIAA SciTech, and CSER (Conference on Systems Engineering Research). Acceptance into these highly competitive venues denotes recognition by peers and experts who value the beneficiary’s advancements in MBSE methodologies, digital twin integration strategies, and complex systems modeling frameworks.
•	Authoring Book Chapters in Foundational MBSE References:
The beneficiary contributed multiple book chapters to the Handbook of Model-Based Systems Engineering (Springer), a seminal reference co-edited by internationally renowned experts, including Norman Augustine (former CEO of Lockheed Martin). These chapters address advanced MBSE applications in manufacturing, Department of Defense case studies, and digital twin-enabled research testbeds, further solidifying the beneficiary’s position as an authoritative voice in the field.
•	Publications Demonstrating Sustained Thought Leadership:
Key works include:
o	“A Model-Based Systems Architecting and Integration Approach Using Interlevel and Intralevel Dependency Matrix” (IEEE Systems Journal), which presents a pioneering framework for analyzing and optimizing system architectures.
o	“Augmenting MBSE with Digital Twin Technology” (IEEE SMC), a paper that sets forth a novel approach to integrating digital twins into MBSE ecosystems, rapidly gaining traction among engineering teams worldwide.
Additionally, the beneficiary’s contributions to chapters focused on MBSE in advanced manufacturing, DoD system analysis, and digital twin-enabled experimentation testbeds highlight a consistent track record of innovative research themes that bridge theoretical rigor with real-world application.
In Summary:
The beneficiary’s authorship and publication record reflect an enduring commitment to advancing the field through rigorous research, innovative methodologies, and globally recognized scholarly contributions. This sustained authorship record satisfies the regulatory standard for authorship of scholarly articles evidencing extraordinary ability, as each publication has garnered attention, citations, and practical implementation by leading institutions and industry practitioners.




--------------------------------------------------------------------------------------

(7) Employment in Critical or Essential Capacity at Distinguished Organizations
The beneficiary has held pivotal roles at some of the most reputable institutions in academia and industry, consistently contributing to advancements in MBSE, digital twin technology, and complex systems architecting. These roles not only demonstrate the beneficiary’s technical expertise but also underline the trust and reliance placed on the beneficiary’s skills by high-profile organizations known for their stringent standards and global impact.
1.	University of Southern California (USC) – Research Assistant (R.A.):
As an R.A. at USC, one of the top-ranked engineering institutions in the United States, the beneficiary worked directly under the mentorship of world-renowned systems engineering expert, Dr. Azad M. Madni. In this role, the beneficiary played an essential part in executing cutting-edge research initiatives in MBSE, digital twins, and AI-enhanced model integration. By shaping research directions, co-authoring high-impact publications, and contributing to NSF-funded projects, the beneficiary’s involvement was instrumental in expanding the frontiers of MBSE and influencing both the academic curriculum and industry best practices.
2.	Raytheon Technologies (RTX) – Research Intern (AI Systems):
During the internship at RTX—a globally recognized aerospace and defense leader—the beneficiary contributed to the Model-Based Digital Thread Process Capability Center. In this capacity, the beneficiary addressed some of the most complex engineering challenges facing RTX’s engineering, manufacturing, and aftermarket organizations. Tasks included the development of ontology-driven frameworks for data interoperability, integration of AI-driven MBSE solutions, and strategic guidance on implementing digital thread methodologies. The beneficiary’s direct involvement in these high-stakes, enterprise-level initiatives was critical in advancing RTX’s capabilities in digital engineering, thereby enhancing product reliability, reducing lifecycle costs, and accelerating time-to-market for next-generation aerospace and defense systems.
3.	Dassault Systèmes – R&D Quality Assurance Engineer:
At Dassault Systèmes—a world leader in 3D design and engineering software—the beneficiary served as a key member of the R&D Quality Assurance team responsible for ensuring the performance, reliability, and quality of CATIA Systems Architecture and simulation applications. Working with renowned aerospace and automotive clients, the beneficiary’s role involved defining test scenarios aligned with customer engineering processes, recommending enhancements to improve user experience, and collaborating with cross-functional teams to strengthen the systems engineering portfolio. This critical capacity position helped shape product development roadmaps, influenced feature implementations that benefited leading aerospace and defense clients, and ensured the reliability of highly complex modeling and simulation tools.
In each of these roles, the beneficiary’s contributions went beyond routine tasks, directly influencing strategy, product direction, and research outcomes. By serving in critical and essential capacities at these distinguished organizations, the beneficiary has demonstrated exceptional leadership, technical acumen, and the ability to meaningfully impact top-tier engineering environments, both academically and industrially.


-----------------------------------------------
9) Other Comparable Evidence
Beyond the standard criteria, the beneficiary has engaged in a broad range of activities that confirm extraordinary ability and leadership in the field of systems engineering, MBSE, and digital twin technology.
•	Leadership in Curriculum and Community Development:
The beneficiary played a pivotal role in the NSF PEER Project curriculum development, introducing digital twin-enabled MBSE concepts into advanced manufacturing education. Additionally, the beneficiary founded and guided the SAE Digital Twin Community, creating an interdisciplinary forum where engineers, researchers, and students share best practices, discuss emerging trends, and collaborate on innovative solutions. These initiatives have influenced both industry training and academic syllabi, fostering a more robust and future-ready workforce.
•	Strategic Industry and Academic Outreach:
The beneficiary organized Acquisition Innovation Research Center (AIRC) workshops, facilitating dialogues between key industry stakeholders, government agencies, and academic researchers to refine acquisition strategies and foster innovation. Serving as Outreach Manager for IEEE SMC and INCOSE collaborations, the beneficiary established new professional groups focused on advancing MBSE, digital twins, and complex systems engineering. This outreach not only expanded professional networks but also guided the discourse on engineering challenges and solutions at a global level.
•	Entrepreneurship and Innovation:
The beneficiary’s entrepreneurial successes—evidenced by multiple awards, selections into esteemed incubators, and recognition in competitions such as the Blackstone Innovation Challenge and Wrigley Sustainability Prize—underscore the beneficiary’s capacity to translate technical expertise into commercially viable, socially impactful solutions. By applying MBSE and digital twin principles to areas like sustainability and supply chain management, the beneficiary’s ventures demonstrate industry foresight, creative problem-solving, and the ability to meet market demands with cutting-edge engineering approaches.
•	Distinguished Lectures and Recognized Expertise:
Lectures delivered at USC’s SAE 549 course were praised by prominent faculty and industry leaders, including Dr. Azad Madni and Gen. Ellen Pawlikowski (Ret., U.S. Air Force), for their intellectual rigor, clarity, and forward-looking insights. These commendations reflect not only the beneficiary’s subject-matter mastery but also the ability to effectively communicate complex topics to diverse audiences, shaping the educational experience of future engineers and influencing high-level practitioners.
•	Technical Chair and Peer Review Roles Demonstrating Judgment of Others’ Work:
Serving as Technical Chair for the 18th Annual Conference on Systems Engineering Research (CSER 2020), the beneficiary managed the peer review process for over 70 research papers. In this capacity, the beneficiary effectively judged the work of other experts, ensuring the conference’s technical rigor and shaping the field’s research agenda. Additionally, the beneficiary served as a peer reviewer for the IEEE Systems Journal and other scholarly publications, receiving acknowledgments from editorial teams for insights and thorough evaluations. These roles underscore the beneficiary’s recognized authority and trusted judgment in assessing and advancing the scholarly contributions of peers in the field.
Collectively, these accomplishments—spanning community building, outreach, entrepreneurial ventures, recognized lectures, and critical roles in evaluating others’ scholarly work—further confirm the beneficiary’s extraordinary ability. They complement the evidence provided under other criteria and underscore a multi-faceted, high-impact career trajectory that continues to shape and propel the discipline of systems engineering.
------------------------------------------------------------------------

Advisory Opinion Letters
The beneficiary anticipates letters of support from preeminent authorities in systems engineering, aerospace, and defense who can attest to the beneficiary’s extraordinary abilities and pioneering contributions. These letters will highlight the beneficiary’s leadership in advancing Model-Based Systems Engineering (MBSE), integrating digital twin methodologies, and influencing the trajectory of complex systems architecting.
•	Distinguished Academic and Research Leaders:
A letter from Dr. Azad M. Madni, a globally recognized leader in MBSE and complex systems engineering, will detail the beneficiary’s role in groundbreaking projects and curriculum development at the University of Southern California. Dr. Madni, whose innovations have shaped MBSE best practices, can attest to the beneficiary’s technical excellence, research rigor, and transformative impact on systems engineering methodologies.
•	High-Level Industry and Government Executives:
A letter from General Ellen M. Pawlikowski (U.S. Air Force, Ret.), a former Commander of Air Force Materiel Command and current member of the RTX Board of Directors, will highlight the beneficiary’s contributions to MBSE-based case studies and their relevance to large-scale defense and aerospace programs. General Pawlikowski’s perspective, informed by decades of leadership in U.S. Air Force R&D initiatives, will provide authoritative confirmation of the beneficiary’s extraordinary skill in architecting resilient, mission-critical systems.
•	Former CEOs, Top Executives, and Renowned Professors:
Additional letters may come from former CEOs, senior industry executives, and distinguished professors from leading universities. These experts can speak to the beneficiary’s collaborative engagements, their influence on strategic engineering roadmaps, and their proven ability to translate cutting-edge research into practical, industry-ready solutions.
Collectively, these advisory opinions will underscore the beneficiary’s exceptional standing in the field. They will confirm that the beneficiary’s work—encompassing MBSE frameworks, digital twin integration, and interdisciplinary applications—represents top-tier, transformative accomplishments recognized by the field’s most respected leaders.



